sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.216.201
    port: 3306
    database: sky_take_out
    username: root
    password: 19990802
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-take-out
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  wechat:
    appid: wx82b4d2ae3b5d14bc
    secret: f7368d30a3b2270b95743f7ce29ad151